version: 2.1

orbs:
  python: cjw296/python-ci@3.1

common: &common
  jobs:
    - python/poetry-run-tests:
        matrix:
          parameters:
            image:
              - cimg/python:3.6
              - cimg/python:3.10

    - python/coverage:
        name: coverage
        requires:
          - python/poetry-run-tests

    - python/release:
        name: release
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * 4"
          filters:
            branches:
              only: master
